title: Michael<br>Van Nuland # your name (or website title) here
logo: "/images/MVN.profilepics.002.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD in Ecology and Evolutionary Biology testtest
  <br><br>
  Plant and soil ecology<br>Microbial bioinformatics<br>Global change biology
  <br><br>
  <a href="https://www.michaelvannuland.com/">View My Research Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
